### ISSUE TITLE
TypeScript .d.ts out of date

### ISSUE THREAD

**Issue by robertDurst** [gampleman/quick_check.js#62]
Not sure if this is still being actively developed -- if not no worries, I hacked what I needed to make it work for my use case -- but if it is, the `.d.ts` file needs to be updated for TypeScript 2.0; my diagnosis is according to [this StackOverFlow post](https://stackoverflow.com/questions/38596833/typescript-ts2036-not-a-module-error-when-working-with-definitelytyped-defini) and based on this error:

```base
quick-check.d.ts' is not a module.

import * as qc from 'quick_check';
```
I could definitely take the time to understand `.d.ts` files and submit a PR myself, it seems as if the differences between the TypeScript circa last update to this file and now is mostly just some rearrangeing of syntax and `export` vs. `declare`... however I may be completely wrong as I just started using TypeScript, more or less, this week 😅

**Comment by gampleman** [comment]
I don't actively maintain this project anymore (and I also don't use typescript myself). I would recommend checking out https://github.com/dubzzz/fast-check, as it is more feature complete and I believe is also written in TypeScript.

**Comment by robertDurst** [comment]
@gampleman ok, thanks! Have a great weekend.
